name: CI & SonarCloud Analysis

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-analyze:
    name: Build, Test and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Desabilita o shallow clone para uma análise mais completa do SonarCloud
          fetch-depth: 0

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install -r requirements_xgboost.txt
          pip install -r requirements_catboost.txt
          pip install -r requirements_lgbm.txt
          pip install -r requirements_tools.txt

      
      - name: Install package
        run: pip install -e .


      - name: Run tests and generate reports
        run: |
          pytest --cov=src --cov-report=xml --cov-report=term-missing --junitxml=test-results.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}