name: CI & SonarCloud Analysis

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-analyze:
    name: Build, Test and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Desabilita o shallow clone para uma análise mais completa do SonarCloud
          fetch-depth: 0

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Instala as dependências de desenvolvimento, que devem incluir as de teste
          pip install -r requirements-dev.txt
          # Instala o seu pacote em modo "editável" para que o pytest o encontre
          pip install -e .

      - name: Run tests and generate reports
        run: |
          # Executa a sua suíte de testes completa na pasta 'tests'
          # --cov=fklearn: Gera cobertura para o pacote 'fklearn'
          # --cov-report=xml: Cria 'coverage.xml' para o SonarCloud
          # --junitxml=test-results.xml: Cria o relatório de resultados de teste para o SonarCloud
          pytest tests/ --cov=fklearn --cov-report=xml --junitxml=test-results.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}